#pre-trained model !!!can't use, not a normal vit
state_key: 'model'
trans_dic:
  #patch_embed.proj.: feature_extractor.body.patch_embedding.patch_embeddings.
  .fc: .linear
  blocks.: feature_extractor.body.blocks.
  .A.: .