---
model: vitdet
gt_box_mode: cccwhd
amp: False
lr: 0.01
w_cls: 1
finetune_epochs: 100
val_interval: 5
spacing:
- 0.703125
- 0.703125
batch_size: 8
patch_size:
- 192
- 192
- 1
val_data_size:
- -1
- -1
- 1
val_patch_size:
- 192
- 192
fg_labels:
- 0
n_input_channels: 1
spatial_dims: 2
model_spatial_dims: 2
score_thresh: 0.02
nms_thresh: 0.22
returned_layers:
- 1
embed_dim: 768
depth: 12
num_heads: 12
dp: 0.1
img_size: 192
out_channels: 256
model_patch_size: 16
window_size: 6
mlp_dim: 3072
scale_factors:
- 2
- 1
window_block_indexes:
- 0
- 1
- 3
- 4
- 6
- 7
- 9
- 10
head_conv_dims:
- -1
- -1
box_head_conv_dims:
- 256
- 256
- 256
box_head_fc_dims:
- 1024
base_anchor_shapes:
- - 6
  - 8
- - 8
  - 6
- - 10
  - 10
balanced_sampler_pos_fraction: 0.6
