---
# architecture
model: vitdet
model_spatial_dims: 2
embed_dim: 3200
depth: 48
num_heads: 25
dp: 0
img_size: 192
out_channels: 256
model_patch_size: 16
window_size: 7
mlp_dim: 12800
n_input_channels: 1
qkv_bias: False
scale_factors:
- 4
- 2
- 1
window_block_indexes:
- 0
- 1
- 3
- 4
- 6
- 7
- 9
- 10
init_values: 1.0
attn_norm_layer: RMS
attn_qk_normalization: True

#dataset & detector
gt_box_mode: cccwhd
spacing:
- 0.703125
- 0.703125
patch_size:
- 192
- 192
- 1
val_data_size:
- -1
- -1
- 1
val_patch_size:
- 192
- 192
fg_labels:
- 0
spatial_dims: 2
score_thresh: 0.02
nms_thresh: 0.22
returned_layers:
- 1
- 2
base_anchor_shapes:
- - 6
  - 8
- - 8
  - 6
- - 10
  - 10
balanced_sampler_pos_fraction: 0.3

#training setting
lr: 0.01
scheduler_step : 30
scheduler_gamma : 0.5
warmup_epochs : 10
warmup_multi : 1
w_cls: 1
finetune_epochs: 300
val_interval: 5
batch_size: 4
amp: False
