---
# architecture
model: vitdet
model_spatial_dims: 2
embed_dim: 768
depth: 12
num_heads: 12
dp: 0.1
img_size: 192
out_channels: 256
model_patch_size: 16
window_size: 6
mlp_dim: 3072
n_input_channels: 1
qkv_bias: True
scale_factors:
- 4
- 2
- 1
window_block_indexes:
- 0
- 1
- 3
- 4
- 6
- 7
- 9
- 10

#dataset & detector
gt_box_mode: cccwhd
spacing:
- 0.703125
- 0.703125
- 1.25
patch_size:
- 192
- 192
- 80
val_data_size:
- -1
- -1
- 1
val_patch_size:
- 192
- 192
fg_labels:
- 0
spatial_dims: 2
score_thresh: 0.02
nms_thresh: 0.22
returned_layers:
- 1
- 2
base_anchor_shapes:
- - 6
  - 8
- - 8
  - 6
- - 10
  - 10
balanced_sampler_pos_fraction: 0.2
num_candidates: 3

#file
data_base_dir: "/orange/bianjiang/tienyu/LUNA16_Images_resample"
data_list_file_path: "/orange/bianjiang/tienyu/LUNA16_datasplit/dataset_fold0.json"
tfevent_path: "/blue/bianjiang/tienyuchang/tfevent_train/luna16"
result_list_file_path: "/blue/bianjiang/tienyuchang/result/result_luna16_vitdet.json"

#training setting
optimizer: adamw
lr: 1.6e-4
wd: 0.2
scheduler_step : 30
scheduler_gamma : 0.5
warmup_epochs : 10
warmup_multi : 1
w_cls: 1
finetune_epochs: 150
val_interval: 5
batch_size: 32
amp: False
model_path: "/blue/bianjiang/tienyuchang/trained_models/model_vitdet_paper_fold0.pt"
