---
model_path: "/blue/bianjiang/tienyuchang/trained_models/model_luna16_vitdet_tmp_fold0.pt"
data_base_dir: "/orange/bianjiang/tienyu/LUNA16_Images_resample"
data_list_file_path: "/orange/bianjiang/tienyu/LUNA16_datasplit/dataset_fold0.json"
tfevent_path: "/blue/bianjiang/tienyuchang/tfevent_train/luna16_2_fold0"
result_list_file_path: "/blue/bianjiang/tienyuchang/result/result_luna16_vitdet_tmp_fold0.json"
