# architecture
model: vit
n_input_channels: 1
spatial_dims: 2
embed_dim : 768
depth : 12
num_heads : 12
qkv_bias: True
dp: 0
out_channels: 256
model_patch_size: 8 
mlp_dim : 3072
decoder_type: 'conv'
conv_bias: True
conv_layernorm: True

#dataset info
dataset: mednist
data_channels: 1
img_size: 64
scale_factor: 4

#train setting
lr: 5.0e-5
scheduler_step: 50
scheduler_gamma: 0.1
warmup_epochs: 10
warmup_multi : 1
finetune_epochs: 200
val_interval: 5
batch_size: 128
amp : False
model_path: "/blue/bianjiang/tienyuchang/super_resol_model/model_mednist.pt"
